#!/usr/bin/env python3.6
"""
A very small command line wrapper to interface with the Viscosity VPN client

https://www.sparklabs.com/support/kb/article/controlling-viscosity-with-applescript-mac/
"""
import argparse
import shlex
import sh


parser = argparse.ArgumentParser()

parser.add_argument('name', help='name of the VPN connection')
parser.add_argument('action', nargs='?', help='connect|disconnect')

args = parser.parse_args()

action = args.action or 'connect'
if action != 'connect':
    action = 'disconnect'

command = shlex.split(f'osascript -e \'tell application "Viscosity" to {action} "{args.name}"\'')

proc = getattr(sh, command[0])

proc(*command[1:], _fg=True)
